on:
  push:
    branches:
      - master

jobs:
  check-releasenotes:
    name: Update tag
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install requirements
        run: |
          git tag -l
