on:
  push:
    branches:
      - master

jobs:
  update-package-version-and-generate-changelog:
    name: Update package version and generate changelog
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install requirements
        run: |
          pip install bump2version==1.0.1
          pip install auto-changelog==0.5.3
          pip install markupsafe==2.0.1

      - name: Run bump_version
        run: |
           chmod +x ./.github/workflows/scripts/bump_version_and_generate_changelog.sh
           .github/workflows/scripts/bump_version_and_generate_changelog.sh
        shell: bash
        env:
          message: ${{ github.event.commits[0].message }}

  update-tag:
    name: Update tag with new package version
    needs: update-package-version-and-generate-changelog
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install requirements
        run: |
          git tag -l

  upload-package:
    name: Upload new versioned package to pypi.org
    needs: update-tag
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install requirements
        run: |
          git tag -l

# Release:
# pip3 install --upgrade build twine
# python3 -m build
# twine upload --repository testpypi dist/*
# twine upload --repository pypi dist/*
